# Generated by Django 4.1.3 on 2022-11-21 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='type',
        ),
        migrations.CreateModel(
            name='IssueType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='issue_type', to='webapp.issue', verbose_name='issue')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='type_issue', to='webapp.type', verbose_name='type issue')),
            ],
        ),
        migrations.AddField(
            model_name='issue',
            name='type',
            field=models.ManyToManyField(blank=True, related_name='issues', through='webapp.IssueType', to='webapp.type'),
        ),
    ]
