# Generated by Django 4.1.3 on 2022-11-21 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_rename_type_name_type_name_alter_issuetype_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issue',
            old_name='type',
            new_name='type_old',
        ),
    ]
