# Generated by Django 4.1.3 on 2022-11-21 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_rename_type_issue_type_old'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='type_old',
            field=models.ManyToManyField(blank=True, related_name='issues_old', through='webapp.IssueType', to='webapp.type'),
        ),
    ]
