# Generated by Django 4.1.3 on 2022-11-21 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_alter_issue_type_old'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='type',
            field=models.ManyToManyField(blank=True, related_name='issues', to='webapp.type'),
        ),
    ]
