# Generated by Django 4.1.3 on 2022-11-21 15:22

from django.db import migrations


def transfer_types(apps, schema_editor):
    Issue = apps.get_model('webapp.Issue')
    for issue in Issue.objects.all():
        issue.type.set(issue.type_old.all())


def rollback_transfer(apps, schema_editor):
    Issue = apps.get_model('webapp.Issue')
    for issue in Issue.objects.all():
        issue.type_old.set(issue.type.all())


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_issue_type'),
    ]

    operations = [
        migrations.RunPython(transfer_types, rollback_transfer)
    ]
