# Generated by Django 4.1.3 on 2022-11-21 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_auto_20221121_2122'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='type_old',
        ),
        migrations.DeleteModel(
            name='IssueType',
        ),
    ]
